InternalVote/urls.py
from django.urls import path
from . import views

# ====================================================

app_name = 'InternalVote'
urlpatterns = [
    # /InternalVote/
    path('', views.index, name='index'),
    # /InternalVote/result
    path('result', views.result, name='result'),
    # /InternalVote/voted
    path('voted', views.voted, name='voted'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

# ====================================================

urlpatterns = [
    path('admin/', admin.site.urls),
    path('InternalVote/', include('InternalVote.urls')),
]

InternalVote/models.py
from django.db import models
from django.utils import timezone

# ====================================================

class Award(models.Model):
    """ Award Loging
    """
    # Award
    AWARD_CHOICES = (              
        ('Freshers', 'Freshers'),   
        ('Growth', 'Growth'),      
        ('Evolution', 'Evolution'),
        ('Reader', 'Reader'),      
    )                              
    award_text = models.CharField(max_length=20, choices=AWARD_CHOICES)

    # Employment
    EMP_CHOICES = (
        ('Regular', 'Regular'),
        ('Part-time', 'Part-time'),
        ('Group', 'Group'),
    )
    employment_text = models.CharField(max_length=10, choices=EMP_CHOICES)
    
    # PrizeWinner
    PERSON_CHOICES = (
    )
    prizewinner_text = models.CharField(max_length=20) # choices=PERSON_CHOICES

    # Reason
    reason_text = models.CharField(max_length=100)

    # Create Date
    create_date = models.DateTimeField(default=timezone.now)

# ====================================================

class AwardMst(models.Model):
    """ Award Description 
    """
    # Award
    award_mst_text = models.CharField(max_length=20)

    # Discription
    discription_text = models.CharField(max_length=100) 

InternalVote/forms.py
from django import forms

# ====================================================

from .models import Award

# ====================================================

class AwardForm(forms.ModelForm):
    """ AwardForm
    """
    class Meta:
        model = Award
        fields = (
          'award_text',
          'employment_text',
          'prizewinner_text',
          'reason_text',
        )
        widgets = {
          'award_text': forms.Select(attrs={'style': "width: 200px; text-align: center;"}),
          'employment_text': forms.Select(attrs={'style': "width: 200px; text-align: center;"}),
          'prizewinner_text': forms.TextInput(attrs={'style': "width: 200px;"}),
          'reason_text': forms.Textarea(attrs={'cols': 40, 
                                               'row': 4,
                                               'style': "width: 500px; height: 110px;"}),
        }

InternalVote/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.urls import reverse

# ====================================================

from .models import Award, AwardMst
from .forms import AwardForm

# ====================================================

def index(request):
    """ Index
    """
    awd_mst = AwardMst.objects.order_by('id')
    if request.method == "POST":
        form = AwardForm(request.POST)
        print('####  DEBUG #####')
        print(form)
        print('##### DEBUG #####')
        if form.is_valid():
            # save
            post = form.save(commit=False)
            print('####  DEBUG #####')
            post.save()
            print(post)
            print('####  DEBUG #####')
            # new form
            form = AwardForm()
            context = {
                'form': form,
		'awd_mst': awd_mst,
            }
            #return render(request, 'InternalVote/index.html', context)
            return HttpResponseRedirect(reverse('InternalVote:voted')) 
    else:
        pass

    form = AwardForm()
    print('####  DEBUG #####')
    print(form)
    print('####  DEBUG #####')
    context = {
        'form': form,
        'awd_mst': awd_mst,
    }
    return render(request, 'InternalVote/index.html', context)

# ====================================================

def voted(request):
    """ Voted
    """
    return render(request, 'InternalVote/voted.html')

# ====================================================

def result(request):
    """ Result
    """
    awd = Award.objects.order_by('create_date')
    context = {
        'awd': awd,
    }
    return render(request, 'InternalVote/result.html', context)

InternalVote/templates/InternalVote/base.html
<!DOCTYPE html>
<html lang="ja">
<!-- head -->
<head>
<meta charset="utf-8">
<title>InternalVote</title>
<!-- style css -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'InternalVote/css/style.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'InternalVote/image/favicon.ico' %}">
</head>
<!-- body -->
<body>
<header>
<h1>InternalVote</h1>
<p>discription</p>
</header>
  {% block content %}{% endblock %}
<!-- link -->
<h3>Links</h3>
<ul>
  <li><a href="{% url 'InternalVote:index' %}">Go to InternalVote Index</a></li>
  <li><a href="{% url 'InternalVote:result' %}">Go to InternalVote Result</a></li>
  <li><a href="{% url 'admin:index' %}">Go to Administrator Index</a></li>
</ul>
<!-- footer -->
<footer>
  <div>
    <small>Copyright &#169; 2019 InternalVote All Rights Reserved.</small>
  </div>
</footer>
<!-- javascript -->
<script type="text/javascript" src="{% static 'InternalVote/js/download_csv.js' %}"></script>
</body>
</html>

InternalVote/templates/InternalVote/index.html
{% extends "InternalVote/base.html" %}
{% block content %}
  <h2>Vote</h2>
  <!-- form -->
  <form method="post" class="">
    <table>
      {% csrf_token %}
      <tbody>
        <tr>
          <th>award_text</th>
          <td>{{ form.award_text }}</td>
        <tr>
        <tr>
          <th>employment_text</th>
          <td>{{ form.employment_text }}</td>
        <tr>
         <tr>
          <th>prizewinner_text</th>
          <td>{{ form.prizewinner_text }}</td>
        <tr>
         <tr>
          <th>reason_text</th>
          <td>{{ form.reason_text }}</td>
        <tr>
      </tbody>
    </table>
    <div class="div-001">
      <!-- submit -->
      <input class="" type="submit" value="Submit">
      <!-- reset -->
      <input class="" type="reset" value="Reset">
    </div>
  </form>
  <h2>Discription</h2>
  <!-- table -->
  {% if awd_mst %}
    <table border="1">
      {% csrf_token %}
      <tr>
        <th>award_text</th>
        <th>discription_text</th>
      </tr>
    {% for dat in awd_mst %}
      <tr>
        <td>{{ dat.award_mst_text }}</td>
        <td>{{ dat.discription_text }}</td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    <p>No dat.</p>
  {% endif %}
{% endblock %}

InternalVote/templates/InternalVote/result.html
{% extends "InternalVote/base.html" %}
{% block content %}
  <h2>Result</h2>
  {% if awd %}
    <table border="1">
    <tr>
    <th>id</th>
    <th>award_text</th>
    <th>employment_text</th>
    <th>prizewinner_text</th>
    <th>reason_text</th>
    <th>create_date</th>
    </tr>
    {% for dat in awd %}
      <tr>
        <td>{{ dat.id }}</td>
        <td>{{ dat.award_text }}</td>
        <td>{{ dat.employment_text }}</td>
        <td>{{ dat.prizewinner_text }}</td>
        <td>{{ dat.reason_text }}</td>
        <td>{{ dat.create_date }}</td>
      </tr>
    {% endfor %}
    </table>
    <div class="div-001">
      <button id="btnPrint">Export HTML table to CSV file</button>
    </div>
  {% else %}
    <p>No dat.</p>
  {% endif %}
{% endblock %}

InternalVote/templates/InternalVote/voted.html
{% extends "InternalVote/base.html" %}
{% block content %}
  <h2>Voted</h2>
  <p>The vote was successful.</p>
{% endblock %}